### ISSUE TITLE
Get information from `git shortlog`

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/name-your-contributors#18]
It's possible a lot of things could be gotten from `git shortlog -s -n`.

**Comment by tgetgood** [comment]
Given how easy it is to get the commit authors from the graphql api, I don't think this will necessary.

**Comment by tgetgood** [comment]
That info is just the number of commits due to each author, no? Between #32 and #35 we'll have that.

**Comment by tgetgood** [comment]
Do we want the commits for every branch? or just `master`?

On further thought, it might be better to get as much as possible from the repo itself without hitting the API. The API also seems to draw a line between Git and GitHub, the former being kind of clunky to access.

**Comment by RichardLitt** [comment]
All branches.

**Comment by tgetgood** [comment]
Actually I have to contradict myself. Getting info locally only works for the repo in the current directory, whereas most of the uses of the tool are about getting info about other things (repos, orgs, users). So using the shortlog could sometimes save a request, but most of the time it won't and we'd just be creating another channel of information. I don't think that would be worth  the extra complexity.

**Comment by RichardLitt** [comment]
Sounds good to me!
