### ISSUE TITLE
Allow dates to be only a date (without hours)

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/name-your-contributors#28]
You shouldn't need to specify hours for the date options of `after` or `before`. 
Requested in #16.

**Comment by tgetgood** [comment]
This works on master right now as is. Any `string` that `new Date(string)` can handle works. It's pretty flexible, see https://tools.ietf.org/html/rfc2822#page-14.

Examples: `"2014"` `"2017-10"` `"2017-10-6"` `"2017-10-10:19:00"`, and so on. 

Incidentally unix timestamps also work: `--after 1507651643`, though that may be less useful.

**Comment by RichardLitt** [comment]
Sweet.
