### ISSUE TITLE
Extend the definition of "contributor"

### ISSUE THREAD

**Issue by tgetgood** [RichardLitt/name-your-contributors#32]
We would like commit authors and people who react to anything in a repo to be included in the definition.

So to that end, we should add two more keys to the returned JSON, `commitAuthors` and `reactors`, and extend the logic to populate them. 

Edit: `PullRequestReviewComment` is a distinct entity to `PullRequestComment`. We should be grabbing those too.

**Comment by tgetgood** [comment]
For `reactors`, do we want to know that Alice reacted to an issue, Bob reacted to 3 issue comments, and Karol reacted to a commit comment? Or do we just care how many times each user reacted as a whole?

**Comment by RichardLitt** [comment]
Just each time, I think. I don't think they make any difference as performances.
