### ISSUE TITLE
Grab amount and type of interaction as needed

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/name-your-contributors#35]
@tgetgood I need a tool that shows me the types of interactions, and the amount of times a user does each, for a repo. 

Basically, I need: RichardLitt committed 4 times, reacted 17 times, commented 5 times, etc...

Can we do this, easily?

**Comment by tgetgood** [comment]
Sure can. I'm currently just uniquifying the lists of contributors; we could add up the number of occurances as we go easily enough.
